version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: com.diffplug.spotless
      versions:
        - 5.12.0
    - dependency-name: org.scalatest:scalatest_2.13
      versions:
        - 3.2.4-M1
        - 3.3.0-SNAP1
        - 3.3.0-SNAP2
        - 3.3.0-SNAP3